dist: trusty
sudo: required

services:
  - docker

env:
  global:
    - V8=6.6.313
  matrix:
    - PHP=7.2
    - PHP=7.2 TEST_PHP_ARGS=-m

before_install:
  # docker on travis doesn't allow anything before FROM, let's fix that
  - sed -i -e "s/:latest/:${V8}/g" Dockerfile
  - docker build -t ${TRAVIS_REPO_SLUG} --build-arg PHP=${PHP} .

script:
  - docker run
    -e TEST_PHP_ARGS
    -v `pwd`:/root/php-v8
    ${TRAVIS_REPO_SLUG}
    bash -c "phpize && ./configure && make test | tee result.txt; ./test-report.sh"
